name: x86-64 Pull and push Docker Image to aliyun
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clean up Docker to free space
      run: |
          docker system prune -a -f
          docker volume prune -f

    - name: Log in to Alibaba Cloud Container Registry
      uses: docker/login-action@v2
      with:
        username: c07082008  # 阿里云用户名或Access Key ID
        password: Binyi123!

    - name: Pull Docker Images and Push to Aliyun Registry
      run: |
        images="${{ github.event.inputs.docker_images }}"
        IFS=',' read -r -a image_array <<< "$images"
        for image in "${image_array[@]}"; do
          # 拉取 Docker 镜像，确保使用 x86-64（amd64）架构
          docker pull "${image}" --platform "linux/amd64"
          
          # 给拉取的镜像打上阿里云仓库的标签
          ali_image="crpi-mrf463e7rbcuftvk.cn-hangzhou.personal.cr.aliyuncs.com/by_repo/by_repo/$(basename ${image}):latest"  # 替换为你自己的阿里云仓库和镜像名称
          docker tag "${image}" "${ali_image}"
          
          # 将镜像推送到阿里云容器镜像服务
          docker push "${ali_image}"
        done

    - name: Clean up Docker images
      run: |
        docker system prune -a -f  # 清理 Docker 镜像以释放空间
